// This file is automatically generated.
import { supabase } from "./client";

export const attachSupabaseAuth = async () => {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  return token ? { Authorization: `Bearer ${token}` } : {};
};
